FROM elixir:1.17.3

EXPOSE 4000

ENV APP_HOME=/usr/src/app \
  HEX_HOME=/opt/hex \
  LANG=C.UTF-8 \
  MIX_HOME=/opt/mix

WORKDIR $APP_HOME

# Install libs
RUN apt-get update && \
    apt-get install -yq \
    ca-certificates \
    inotify-tools \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# install supporting tools
RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix archive.install hex phx_new

# copy dependencies
COPY ./config config
COPY ./mix.exs ./mix.lock ./.formatter.exs ./

RUN MIX_ENV=dev mix do deps.get, deps.compile, compile
RUN MIX_ENV=test mix do deps.get deps.compile, compile

COPY ./assets assets
COPY ./lib lib
COPY ./priv priv
COPY ./test test

CMD ["elixir", "--name", "torrent-video@127.0.0.1", "--cookie", "monster", "-S", "mix", "phx.server"]